# Generated by Django 3.2.13 on 2022-05-27 11:16

from django.db import migrations, models
import saleor.core.db.fields
import saleor.core.utils.editorjs


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0166_update_publication_date_and_available_for_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="longDescription",
            field=saleor.core.db.fields.SanitizedJSONField(
                blank=True,
                null=True,
                sanitizer=saleor.core.utils.editorjs.clean_editor_js,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="longDescription_plaintext",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="longDescription",
            field=saleor.core.db.fields.SanitizedJSONField(
                blank=True,
                null=True,
                sanitizer=saleor.core.utils.editorjs.clean_editor_js,
            ),
        ),
    ]
