# Generated by Django 3.2.13 on 2022-06-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0167_auto_20220527_1316"),
        ("product", "0170_rewrite_digitalcontenturl_orderline_relation"),
    ]

    operations = []
