# Generated by Django 3.2.15 on 2022-09-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0171_merge_20220623_1825'),
        ('product', '0175_alter_productmedia_product'),
    ]

    operations = [
    ]
