# Generated by Django 3.2.15 on 2022-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0176_merge_20220912_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='longDescription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='longDescription_plaintext',
        ),
        migrations.RemoveField(
            model_name='producttranslation',
            name='longDescription',
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
