# Generated by Django 3.2.15 on 2022-11-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0176_merge_20221007_1324'),
        ('product', '0177_auto_20220915_1233'),
    ]

    operations = [
    ]
